### ISSUE TITLE
Failed to build on Debian 11

### ISSUE THREAD

**Issue by mancellin** [htool-ddm/htool#42]
I'm trying to build htool on Debian 11, by following the instructions of the Readme.

At `cmake ..`, I get the following error:
```
  Imported target "MPI::MPI_CXX" includes non-existent path

    "/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
`openmpi` is installed and there is a `/usr/lib/x86_64-linux-gnu/openmpi/` directory, but no `include` subdirectory.

Any clue of what is going on?

**Comment by PierreMarchand20** [comment]
Note that you do not need to really install htool. Since it is a header library, you can just give the path to the `include` directory when trying to compile. The README instruction are just here in case you want to copy htool's include directory to the one of your system to make it accessible via your PATH. They should work though ^^'

What version of cmake are you using? And how did you install openmi? I will try to reproduce this.

**Comment by PierreMarchand20** [comment]
Did you install both `openmpi-bin`and `libopenmpi-dev` using `apt-get` ?

**Comment by mancellin** [comment]
> Note that you do not need to really install htool.

Actually I had first the issue when installing htool_python, and then tried htool itself to locate the error.

> Did you install both openmpi-bin and libopenmpi-dev using apt-get ?

Hum, indeed, I did `sudo apt install "openmpi*"`, so I probably missed `libopenmpi`. I'll check that later today.

**Comment by mancellin** [comment]
It works now, thank you.

Maybe you could add a line with a list of Debian/Ubuntu packages to the installation instructions?
For instance, I installed pybind11, but it is not mentioned anywhere in the Readme of htool_python.

**Comment by PierreMarchand20** [comment]
That's a good idea! For pybind11, you do not need to install pybind11 a priori since it is already there as a submodule : https://github.com/htool-ddm/htool_python/tree/main/lib did you clone with the submodules ?

**Comment by PierreMarchand20** [comment]
It could be another missing [package](https://stackoverflow.com/questions/4097339/missing-python-h-while-trying-to-compile-a-c-extension-module), I will try to update README for htool-python, and refer to the docker images used to test htool and htool-python (see for example https://github.com/htool-ddm/htool_testing_environments/blob/master/debian/Dockerfile)
